name: CI/CD Pipeline

on:
  push:
    branches:
      - main # 监听main分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        run: |
          # Build and push the backend image
          docker build -t cnhjp/demo-backend:latest -f backend/Dockerfile backend/
          docker push cnhjp/demo-backend:latest

          # Build and push the frontend image
          docker build -t cnhjp/demo-frontend:latest -f frontend/Dockerfile frontend/
          docker push cnhjp/demo-frontend:latest

      - name: Deploy to Server
        run: |
          echo "${{ secrets.TCT_SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          eval "$(ssh-agent -s)"
          ssh-add id_rsa
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.TCT_SSH_PORT }} root@${{ secrets.TCT_SSH_IP }} "
            docker stop demo-frontend || true && \
            docker rm demo-frontend || true && \
            docker stop demo-backend || true && \
            docker rm demo-backend || true && \
            docker image rm cnhjp/demo-backend || true && \
            docker image rm cnhjp/demo-frontend || true && \
            docker pull cnhjp/demo-backend && \
            docker pull cnhjp/demo-frontend && \
            docker run -d --name demo-frontend -p 8080:8080 cnhjp/demo-frontend && \
            docker run -d --name demo-backend -p 5000:5000 cnhjp/demo-backend"
